name: CI

on:
  push:
    branches: ['main', 'renovate/**']
  pull_request:
    branches: ['main']

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false  # Ensure the image is not pushed
          tags: |
            temp-image:latest
          platforms: linux/amd64,linux/arm64

      - name: Test Docker image
        run: |
          docker run --rm temp-image:latest /bin/sh -c "echo 'Docker image built successfully!'"

          
